Repository FIFA-Corp/fitnest, pull requests merged in 2022-10, with the labels that each got.

#38 Improvement layout and formatting
  package-lock.json
  src/component/brand-container.tsx
  src/component/category-container.tsx
  src/component/layout/navbar.tsx
  src/component/product-container.tsx
  src/component/ui/card/brand-category-card.tsx
  src/component/ui/card/product-card.tsx
  src/routes/home.tsx
  src/routes/products/productId.tsx
Labels: enhancement

#61 Handle submit search without rerender to whole app
  src/component/layout/navbar.tsx
  src/routes/products/products.tsx
Labels: bug, enhancement

#79 fix product is available in cart but web show not found
  src/component/layout/cart.tsx
Labels: bug, help wanted
